version: '3.8'

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "1212:1212"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=1212
    volumes:
      - ./:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: